# Definições Padrão (Fallback) caso alguma rota não tenha config específica
defaults:
  max_tokens: 100        # Capacidade padrão do balde (Burst)
  refill_per_sec: 10     # Taxa de recarga padrão
  penalty: 1             # Custo padrão por requisição
  global_timeout: 2000     # Timeout global para todas as rotas em ms

routes:
  - path: "/dict/{ownerId}/key"
    host: "http://localhost:3000"
    method: "GET"
    max_tokens: 500      
    refill_per_sec: 200   
    penalty: 1            
    bucket_key: "ownerId"
